### ISSUE TITLE
Fontawesome scss import breaks the build

### ISSUE THREAD

**Issue by cham11ng** [cham11ng/face-recognition#13]
Fontawesome SCSS import breaks the build

`main.scss`

I had to comment on this line
// @import 'node_modules/font-awesome/scss/font-awesome';

This will fix as mentioned in README.md

> The icon may not appear after you build in your local. Simply checkout `app.css`.

**Comment by mgeorgiou** [comment]
I can take a look

**Comment by cham11ng** [comment]
Fixed by https://github.com/cham11ng/face-recognition/pull/15

This will be closed as soon as the dev branch is merged in master.
